### ISSUE TITLE
Instagram API stopped working

### ISSUE THREAD

**Issue by petersg83** [simov/purest-providers#3]
Hi,

From what I understood the Instragram API changed: https://www.instagram.com/developer/

I think the new config is now (https://developers.facebook.com/docs/instagram-basic-display-api/guides/getting-profiles-and-media) :

```
          "instagram": {
            "https://graph.instagram.com": {
              "__domain": {
                "auth": {
                  "qs": {"access_token": "[0]"}
                }
              },
              "{endpoint}": {
                "__path": {
                  "alias": "__default",
                }
              }
            }
          },
```

Becarefull, the answer's structure of the instagram API is different, so it is a breaking change

**Comment by simov** [comment]
Yes, they are moving away from the old API. In Purest v3 you can override the default config https://simov.gitbooks.io/purest/content/docs/02-provider-config.html

Let me know if that works for you.

**Comment by petersg83** [comment]
Yes I was able to override the config and make it work :)
Should `purest-providers` be updated? I can make a PR

**Comment by simov** [comment]
Sure, as far as I understand the legacy Instagram API has already been deprecated and shut down, so I don't think it will be a breaking change for anyone.

**Comment by petersg83** [comment]
Totally ! I'll do that :)
